<?php

namespace AppBundle\Repository;

use AppBundle\Entity\Task;
use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\NonUniqueResultException;
use Doctrine\ORM\NoResultException;

/**
 * TaskRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TaskRepository extends EntityRepository
{
    /**
     * @param int $listId
     * @return Task[]
     */
    public function getListTasks($listId)
    {
        return $this->createQueryBuilder('t')
            ->where('t.todoList = :id')->setParameter('id', $listId)
            ->getQuery()
            ->getResult();
    }

    /**
     * @param int $id
     * @param int $listId
     * @return Task
     * @throws NoResultException If the query returned no result.
     * @throws NonUniqueResultException If the query result is not unique.
     */
    public function getTask($id, $listId)
    {
        return $this->createQueryBuilder('t')
            ->where('t.id = :id')->setParameter('id', $id)
            ->andWhere('t.todoList = :listId')->setParameter('listId', $listId)
            ->getQuery()
            ->getSingleResult();
    }
}
