<?php

namespace AppBundle\Repository;

use AppBundle\Entity\TodoList;
use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\NonUniqueResultException;
use Doctrine\ORM\NoResultException;

/**
 * TodoListRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TodoListRepository extends EntityRepository
{
    /**
     * @return TodoList[]
     */
    public function getAvailableLists()
    {
        return $this->createQueryBuilder('tl')
            ->select('t, tl')
            ->join('tl.tasks', 't')
            ->getQuery()
            ->getResult();
    }

    /**
     * @param $id
     * @return TodoList
     * @throws NonUniqueResultException If the query result is not unique.
     * @throws NoResultException        If the query returned no result.
     */
    public function getList($id)
    {
        return $this->createQueryBuilder('tl')
            ->select('t, tl')
            ->join('tl.tasks', 't')
            ->where('tl.id = :id')->setParameter('id', $id)
            ->getQuery()
            ->getSingleResult();
    }
}
