<?php

namespace App\Repository;

use App\Entity\Task;
use Doctrine\Bundle\DoctrineBundle\Repository\ServiceEntityRepository;
use Doctrine\Common\Persistence\ManagerRegistry;
use Doctrine\ORM\NonUniqueResultException;
use Doctrine\ORM\NoResultException;

/**
 * TaskRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TaskRepository extends ServiceEntityRepository
{
    /**
     * @param ManagerRegistry $registry
     */
    public function __construct(ManagerRegistry $registry)
    {
        parent::__construct($registry, Task::class);
    }

    /**
     * @param int $listId
     * @return Task[]
     */
    public function getListTasks($listId)
    {
        return $this->createQueryBuilder('t')
            ->where('t.todoList = :id')->setParameter('id', $listId)
            ->getQuery()
            ->getResult();
    }

    /**
     * @param int $id
     * @param int $listId
     * @return Task
     * @throws NoResultException If the query returned no result.
     * @throws NonUniqueResultException If the query result is not unique.
     */
    public function getTask($id, $listId)
    {
        return $this->createQueryBuilder('t')
            ->where('t.id = :id')->setParameter('id', $id)
            ->andWhere('t.todoList = :listId')->setParameter('listId', $listId)
            ->getQuery()
            ->getSingleResult();
    }
}
